// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

package ars_miner_srv_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Data struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Account              string   `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{0}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *Data) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *Data) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type RequestLogin struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Account              string   `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestLogin) Reset()         { *m = RequestLogin{} }
func (m *RequestLogin) String() string { return proto.CompactTextString(m) }
func (*RequestLogin) ProtoMessage()    {}
func (*RequestLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{1}
}

func (m *RequestLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestLogin.Unmarshal(m, b)
}
func (m *RequestLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestLogin.Marshal(b, m, deterministic)
}
func (m *RequestLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestLogin.Merge(m, src)
}
func (m *RequestLogin) XXX_Size() int {
	return xxx_messageInfo_RequestLogin.Size(m)
}
func (m *RequestLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestLogin.DiscardUnknown(m)
}

var xxx_messageInfo_RequestLogin proto.InternalMessageInfo

func (m *RequestLogin) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *RequestLogin) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *RequestLogin) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ResponseLogin struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Data                 *Data    `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseLogin) Reset()         { *m = ResponseLogin{} }
func (m *ResponseLogin) String() string { return proto.CompactTextString(m) }
func (*ResponseLogin) ProtoMessage()    {}
func (*ResponseLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{2}
}

func (m *ResponseLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseLogin.Unmarshal(m, b)
}
func (m *ResponseLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseLogin.Marshal(b, m, deterministic)
}
func (m *ResponseLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseLogin.Merge(m, src)
}
func (m *ResponseLogin) XXX_Size() int {
	return xxx_messageInfo_ResponseLogin.Size(m)
}
func (m *ResponseLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseLogin.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseLogin proto.InternalMessageInfo

func (m *ResponseLogin) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResponseLogin) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ResponseLogin) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type RequestRegister struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestRegister) Reset()         { *m = RequestRegister{} }
func (m *RequestRegister) String() string { return proto.CompactTextString(m) }
func (*RequestRegister) ProtoMessage()    {}
func (*RequestRegister) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{3}
}

func (m *RequestRegister) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestRegister.Unmarshal(m, b)
}
func (m *RequestRegister) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestRegister.Marshal(b, m, deterministic)
}
func (m *RequestRegister) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestRegister.Merge(m, src)
}
func (m *RequestRegister) XXX_Size() int {
	return xxx_messageInfo_RequestRegister.Size(m)
}
func (m *RequestRegister) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestRegister.DiscardUnknown(m)
}

var xxx_messageInfo_RequestRegister proto.InternalMessageInfo

func (m *RequestRegister) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *RequestRegister) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ResponseRegister struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Data                 *Data    `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseRegister) Reset()         { *m = ResponseRegister{} }
func (m *ResponseRegister) String() string { return proto.CompactTextString(m) }
func (*ResponseRegister) ProtoMessage()    {}
func (*ResponseRegister) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{4}
}

func (m *ResponseRegister) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseRegister.Unmarshal(m, b)
}
func (m *ResponseRegister) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseRegister.Marshal(b, m, deterministic)
}
func (m *ResponseRegister) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseRegister.Merge(m, src)
}
func (m *ResponseRegister) XXX_Size() int {
	return xxx_messageInfo_ResponseRegister.Size(m)
}
func (m *ResponseRegister) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseRegister.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseRegister proto.InternalMessageInfo

func (m *ResponseRegister) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResponseRegister) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ResponseRegister) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Data)(nil), "ars.miner.srv.user.Data")
	proto.RegisterType((*RequestLogin)(nil), "ars.miner.srv.user.RequestLogin")
	proto.RegisterType((*ResponseLogin)(nil), "ars.miner.srv.user.ResponseLogin")
	proto.RegisterType((*RequestRegister)(nil), "ars.miner.srv.user.RequestRegister")
	proto.RegisterType((*ResponseRegister)(nil), "ars.miner.srv.user.ResponseRegister")
}

func init() { proto.RegisterFile("proto/user/user.proto", fileDescriptor_9b283a848145d6b7) }

var fileDescriptor_9b283a848145d6b7 = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x92, 0x5f, 0x4b, 0xc3, 0x30,
	0x14, 0xc5, 0xd7, 0xad, 0xd3, 0x79, 0xa7, 0x38, 0x82, 0x42, 0xe9, 0x53, 0x8d, 0x3e, 0xec, 0x41,
	0x22, 0xcc, 0xaf, 0x20, 0xe8, 0x83, 0xf8, 0x10, 0x50, 0x9f, 0x63, 0x7b, 0x19, 0x41, 0x4c, 0x6a,
	0x6e, 0x3a, 0x3f, 0x96, 0x5f, 0x51, 0x9a, 0xfe, 0xa1, 0xe8, 0x1c, 0xf8, 0xe2, 0x4b, 0xc9, 0xb9,
	0x3d, 0xfd, 0x71, 0xee, 0x69, 0xe0, 0xb4, 0x74, 0xd6, 0xdb, 0xab, 0x8a, 0xd0, 0x85, 0x87, 0x08,
	0x9a, 0x31, 0xe5, 0x48, 0xbc, 0x69, 0x83, 0x4e, 0x90, 0xdb, 0x88, 0xfa, 0x0d, 0xbf, 0x83, 0xf8,
	0x46, 0x79, 0xc5, 0x16, 0x30, 0xa9, 0x74, 0x91, 0x44, 0x59, 0xb4, 0x9c, 0xc8, 0xfa, 0xc8, 0x12,
	0xd8, 0x57, 0x79, 0x6e, 0x2b, 0xe3, 0x93, 0x71, 0x16, 0x2d, 0x0f, 0x64, 0x27, 0xd9, 0x09, 0x4c,
	0xbd, 0x7d, 0x45, 0x93, 0x4c, 0xc2, 0xbc, 0x11, 0xfc, 0x09, 0x0e, 0x25, 0xbe, 0x57, 0x48, 0xfe,
	0xde, 0xae, 0xb5, 0xf9, 0x13, 0x31, 0x85, 0x59, 0xa9, 0x88, 0x3e, 0xac, 0x2b, 0x5a, 0x68, 0xaf,
	0x39, 0xc1, 0x91, 0x44, 0x2a, 0xad, 0x21, 0x6c, 0xc0, 0x0c, 0xe2, 0xdc, 0x16, 0xd8, 0x92, 0xc3,
	0x99, 0x65, 0x30, 0x2f, 0x90, 0x72, 0xa7, 0x4b, 0xaf, 0xad, 0x69, 0xf1, 0xc3, 0x11, 0xbb, 0x84,
	0xb8, 0x50, 0x5e, 0x05, 0xfc, 0x7c, 0x95, 0x88, 0x9f, 0x5d, 0x88, 0xba, 0x08, 0x19, 0x5c, 0xfc,
	0x16, 0x8e, 0xdb, 0x65, 0x24, 0xae, 0x35, 0x79, 0x74, 0xc3, 0xf4, 0xd1, 0xef, 0xe9, 0xc7, 0xdf,
	0xd2, 0x6f, 0x60, 0xd1, 0xa5, 0xef, 0x49, 0xff, 0xb0, 0xc0, 0xea, 0x33, 0x82, 0xf8, 0x91, 0xd0,
	0xb1, 0x07, 0x98, 0x36, 0xb5, 0x65, 0xdb, 0xbe, 0x18, 0xfe, 0xb1, 0xf4, 0x6c, 0xbb, 0x63, 0xd0,
	0x3d, 0x1f, 0xb1, 0x67, 0x98, 0xf5, 0x8b, 0x9c, 0xef, 0x40, 0x76, 0xa6, 0xf4, 0x62, 0x17, 0xb5,
	0x73, 0xf1, 0xd1, 0xcb, 0x5e, 0xb8, 0xa4, 0xd7, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x48, 0xa3,
	0x31, 0xf9, 0xbd, 0x02, 0x00, 0x00,
}
