// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

package ars_miner_srv_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Data struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Account              string   `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{0}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *Data) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *Data) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type RequestLogin struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Account              string   `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestLogin) Reset()         { *m = RequestLogin{} }
func (m *RequestLogin) String() string { return proto.CompactTextString(m) }
func (*RequestLogin) ProtoMessage()    {}
func (*RequestLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{1}
}

func (m *RequestLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestLogin.Unmarshal(m, b)
}
func (m *RequestLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestLogin.Marshal(b, m, deterministic)
}
func (m *RequestLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestLogin.Merge(m, src)
}
func (m *RequestLogin) XXX_Size() int {
	return xxx_messageInfo_RequestLogin.Size(m)
}
func (m *RequestLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestLogin.DiscardUnknown(m)
}

var xxx_messageInfo_RequestLogin proto.InternalMessageInfo

func (m *RequestLogin) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *RequestLogin) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *RequestLogin) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ResponseLogin struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Data                 *Data    `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseLogin) Reset()         { *m = ResponseLogin{} }
func (m *ResponseLogin) String() string { return proto.CompactTextString(m) }
func (*ResponseLogin) ProtoMessage()    {}
func (*ResponseLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{2}
}

func (m *ResponseLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseLogin.Unmarshal(m, b)
}
func (m *ResponseLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseLogin.Marshal(b, m, deterministic)
}
func (m *ResponseLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseLogin.Merge(m, src)
}
func (m *ResponseLogin) XXX_Size() int {
	return xxx_messageInfo_ResponseLogin.Size(m)
}
func (m *ResponseLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseLogin.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseLogin proto.InternalMessageInfo

func (m *ResponseLogin) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResponseLogin) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ResponseLogin) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Data)(nil), "ars.miner.srv.user.Data")
	proto.RegisterType((*RequestLogin)(nil), "ars.miner.srv.user.RequestLogin")
	proto.RegisterType((*ResponseLogin)(nil), "ars.miner.srv.user.ResponseLogin")
}

func init() { proto.RegisterFile("proto/user/user.proto", fileDescriptor_9b283a848145d6b7) }

var fileDescriptor_9b283a848145d6b7 = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xcd, 0x4a, 0xc4, 0x30,
	0x10, 0x80, 0xad, 0xed, 0xfa, 0x33, 0xab, 0x20, 0x83, 0x42, 0xd8, 0x53, 0xed, 0x69, 0x0f, 0x12,
	0x61, 0x7d, 0x05, 0x0f, 0x1e, 0xc4, 0x43, 0xc0, 0xbd, 0xc7, 0x66, 0x90, 0x20, 0x66, 0x6a, 0x26,
	0xd5, 0xd7, 0x97, 0xa6, 0x55, 0x0a, 0xf6, 0xe2, 0x25, 0xcc, 0x37, 0x99, 0x7c, 0x49, 0x66, 0xe0,
	0xaa, 0x8b, 0x9c, 0xf8, 0xb6, 0x17, 0x8a, 0x79, 0xd1, 0x99, 0x11, 0x6d, 0x14, 0xfd, 0xee, 0x03,
	0x45, 0x2d, 0xf1, 0x53, 0x0f, 0x3b, 0xcd, 0x03, 0x54, 0xf7, 0x36, 0x59, 0xbc, 0x80, 0xb2, 0xf7,
	0x4e, 0x15, 0x75, 0xb1, 0x2d, 0xcd, 0x10, 0xa2, 0x82, 0x63, 0xdb, 0xb6, 0xdc, 0x87, 0xa4, 0x0e,
	0xeb, 0x62, 0x7b, 0x6a, 0x7e, 0x10, 0x2f, 0x61, 0x95, 0xf8, 0x8d, 0x82, 0x2a, 0x73, 0x7e, 0x84,
	0x66, 0x0f, 0x67, 0x86, 0x3e, 0x7a, 0x92, 0xf4, 0xc8, 0xaf, 0x3e, 0xfc, 0xcb, 0xb8, 0x81, 0x93,
	0xce, 0x8a, 0x7c, 0x71, 0x74, 0x93, 0xf4, 0x97, 0x1b, 0x81, 0x73, 0x43, 0xd2, 0x71, 0x10, 0x1a,
	0xc5, 0x08, 0x55, 0xcb, 0x8e, 0x26, 0x73, 0x8e, 0xb1, 0x86, 0xb5, 0x23, 0x69, 0xa3, 0xef, 0x92,
	0xe7, 0x30, 0xe9, 0xe7, 0x29, 0xbc, 0x81, 0xca, 0xd9, 0x64, 0xb3, 0x7e, 0xbd, 0x53, 0xfa, 0x6f,
	0x2f, 0xf4, 0xd0, 0x08, 0x93, 0xab, 0x76, 0x7b, 0xa8, 0x9e, 0x85, 0x22, 0x3e, 0xc1, 0x6a, 0xbc,
	0xb4, 0x5e, 0x3a, 0x30, 0xff, 0xef, 0xe6, 0x7a, 0xb9, 0x62, 0xf6, 0xf2, 0xe6, 0xe0, 0xe5, 0x28,
	0x4f, 0xe2, 0xee, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x44, 0x12, 0x7b, 0xc9, 0xa2, 0x01, 0x00, 0x00,
}
